name: Nightly Gradle Build

on:
  schedule:
    - cron: '0 0 * * *' #Runs daily at midnight
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
          cache-dependency-path: |
            **/*.gradle*
            **/gradle.properties
            **/gradle-wrapper.properties
            **/gradle.lockfile
            src/main/resources/hbm_at.cfg

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Find mod jar
        run: |
          FILE=$(ls build/libs | grep -E '^NTM-CE.*\.jar$' | grep -vE '(-dev|-sources)' | head -n1)
          echo "FILE=$FILE" >> $GITHUB_ENV


      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nightly-build
          path: build/libs/

      - name: Create nightly tag
        id: tag
        run: |
          DATE=$(date +'%Y-%m-%d')
          TAG=nightly-$DATE
          echo "TAG=$TAG" >> "$GITHUB_ENV"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -f $TAG
          git push --force origin $TAG

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: "Nightly Build ${{ env.TAG }}"
          prerelease: true
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete old nightly releases
        uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          keep_latest: 10
          delete_tags: true
          delete_tag_pattern: '^nightly-'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name:  Upload release to CF
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          curl -X POST \
            -H "x-api-token: $CF_API_TOKEN" \
            -F "metadata={\"changelog\":\"${{ github.event.release.body }}\",\"changelogType\":\"markdown\",\"releaseType\":\"beta\",\"gameVersions\":[6756]}" \
            -F "file=@build/libs/${FILE}" \
            https://minecraft.curseforge.com/api/projects/1312314/upload-file